### ISSUE TITLE
peer2peer scenario

### ISSUE THREAD

**Issue by joeblew99** [dart-lang/json_rpc_2#16]
Does this support bidirectional p2p between the browser and server ?
I was looking at the tests and could not see that. 

This looks like an amazing library.

**Comment by nex3** [comment]
Yeah! Check out the [`Peer`](https://www.dartdocs.org/documentation/json_rpc_2/2.0.3/json_rpc_2/Peer-class.html) class. Note that the JSON RPC 2 protocol doesn't have explicit peer-to-peer support; it's just modeled as each endpoint having both a client and a server, so that's what the `Peer` class implements.

**Comment by joeblew99** [comment]
ok thanks. works for me..
