### ISSUE TITLE
Enormous memory footprint, when client has a lot of pending requests

### ISSUE THREAD

**Issue by deftomat** [dart-lang/json_rpc_2#7]
We have an application, which in some circumstances store messages in queue (paused stream) and send them all later. For example, when target is down and our application waiting for new connection.

However, if a lot of messages are sended by [sendRequest()](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/client.dart#L94) at the same time, than the memory footprint of application is enormous due to stored stackTraces in [_pendingRequests](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/client.dart#L32).

Maybe, there could be an optional parameter in [sendRequest()](https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/client.dart#L94), which prevent to build a Chain instance.

**Comment by nex3** [comment]
This is a request I've heard before; it seems reasonable. If you want to take a crack at it, @deftomat, it shouldn't be too hard to work up a patch.

I think it makes the most sense to define this on a per-client basis so that a user can easily enable it in debug mode and disable it otherwise. Ideally it would be a named constructor parameter, but since both constructors take positional optional arguments that would be a breaking change. For now the best solution is probably to add a mutable `storeRequestTraces` field that the user can set.
